export const cards = [
    {
        id: 1,
        title: 'Necesitas arreglar tu',
        subTitle: 'Heladera?',
        img: '/img/heladera.png',
    },
    {
        id: 2,
        title: 'Necesito el mejor',
        subTitle: 'Jardinero.',
        img: '/img/jardinero.png',
    },
    {
        id: 3,
        title: 'Tengo problemas',
        subTitle: 'de Gas...',
        img: '/img/gasista.png',
    },
    {
        id: 4,
        title: 'Quiero arreglar mi',
        subTitle: 'Celular...',
        img: '/img/celular.png',
    },
    {
        id: 5,
        title: 'Quiero pintar mi',
        subTitle: 'Casa...',
        img: '/img/pintores.png',
    },
    {
        id: 6,
        title: 'Tengo obras que ',
        subTitle: 'Hacer en casa...',
        img: '',
    },
    {
        id: 7,
        title: 'Solicitar un',
        subTitle: 'Carpintero...',
        img: '',
    },
    {
        id: 8,
        title: 'Quiero contratar',
        subTitle: 'un Herrero.',
        img: '',
    },
    {
        id: 9,
        title: 'Necesito contratar',
        subTitle: 'Pintores...',
        img: '',
    },
]

export const projects = [
    {
        id: 1,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        cat: "Asador",
        username: "Walter Ferreyra",
    },
    {
        id: 2,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        cat: "Asador",
        username: "Walter Ferreyra",
    },
    {
        id: 3,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        cat: "Asador",
        username: "Walter Ferreyra",
    },
    {
        id: 4,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        cat: "Asador",
        username: "Walter Ferreyra",
    },
    {
        id: 5,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        cat: "Asador",
        username: "Walter Ferreyra",
    },
    {
        id: 6,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        cat: "Asador",
        username: "Walter Ferreyra",
    },
    {
        id: 7,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        cat: "Asador",
        username: "Walter Ferreyra",
    },
    {
        id: 8,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        cat: "Asador",
        username: "Walter Ferreyra",
    },
    {
        id: 9,
        img: '/img/asador.jpg' ,
        pp: '/img/pp.png',
        cat: "Asador",
        username: "Walter Ferreyra",
    }
]

export const laburos = [
    {
        id: 1,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 1",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 2,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 2",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 3,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 3",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 4,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 4",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 5,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 5",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 6,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 6",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 7,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 7",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 8,
        img:'/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 8",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 9,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 9",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 10,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 10",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 11,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 11",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 12,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 12",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 13,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 13",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 14,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 14",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 15,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Laburo 15",
        star: 5,
        username: "Walter Ferreyra",
    },

]


export const ofertas = [
    {
        id: 1,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"La Plata, Arg",
    },
    {
        id: 2,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Bahía Blanca, Arg",
    },

    {
        id: 3,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Buenos Aires, Arg",
    },

    {
        id: 4,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },

    {
        id: 5,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },

    {
        id: 6,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },

    {
        id: 7,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },

    {
        id: 8,
        img:'/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },

    {
        id: 9,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },
    {
        id: 10,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },
    {
        id: 11,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },
    {
        id: 12,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },
    {
        id: 13,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },
    {
        id: 14,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },
    {
        id: 15,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        title: "Asador",
        desc: "Necesito un asador de unos 2,5m",
        star: 5,
        username: "Ana Ramirez",
        ubi:"Santa Fe, Arg",
    },

]


export const trabajadores = [
    {
        id: 1,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 2,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 3,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 4,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 5,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 6,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 7,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 8,
        img:'/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },

    {
        id: 9,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 10,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 11,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 12,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 13,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 14,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },
    {
        id: 15,
        img: '/img/asador.jpg',
        pp: '/img/pp.png',
        desc: "Profesional en albañileria",
        star: 5,
        username: "Walter Ferreyra",
    },

]