import { Inter } from "next/font/google";
import Header from "@/components/header/Header.jsx";
import Footer from "@/components/footer/Footer.jsx";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <Link href="/usuarios" >Perfil</Link>
      </body>
    </html>
  );
}
